name: Run Notebook

on:
  push:
    branches:
      - main  # This will trigger the workflow when you push to the 'main' branch

jobs:
  run_notebook:
    runs-on: ubuntu-latest  # This tells GitHub to run the job on an Ubuntu machine

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set the secret API key as an environment variable
      - name: Set API Key as environment variable
        run: echo "SECRET_MENA_API_KEY=${{ secrets.SECRET_MENA_API_KEY }}" >> $GITHUB_ENV

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Adjust the Python version as needed

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a 'requirements.txt' file with necessary libraries

      # Step 5: Run the Jupyter notebook
      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute your_notebook.ipynb
